version: '3.8'
services:
  cms:
    build: .
    ports:
      - "8085:80"
    networks:
      - cms-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
    ports:
      - "3307:3306"
    networks:
      - cms-network
networks:
  cms-network:
    driver: bridge
